
version: "3.8"
services:
  mongodb_meals_microservice:
    image: mongo
    container_name: mongodb_meals_microservice
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongodb_orders_microservice:
    image: mongo
    container_name: mongodb_orders_microservice
    ports:
      - "27018:27018"
    command: mongod --port 27018
    volumes:
      - data:/data
    environment:
      - PORT=27018
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express-meals:
    image: mongo-express
    container_name: mongo-express-meals
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb_meals_microservice

  mongo-express-orders:
    image: mongo-express
    container_name: mongo-express-orders
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_PORT=27018
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb_orders_microservice

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    restart: always
    ports:
      - "9411:9411"

volumes:
  data: {}

networks:
  default:
    name: mongodb_network