spring:
  profiles:
    default: dev
  application:
    name: payment-microservice
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: order-microservice
            client-secret: OlvmxZK2wAFeGQW03hejWXw3YhcGdHT7
        provider:
          keycloak:
            token-uri: http://localhost:8180/auth/realms/ourkitchen-yourhealth/protocol/openid-connect/token
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
payU:
  process:
    payment:
      uri: https://secure.snd.payu.com/api/v2_1/orders
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/payment_database
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka









